config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names:{sign_in: 'login', sign_out:'logout',sign_up: 'register' }
    



    
    root to: 'page#home'    
    
    get 'about_me', to: 'page#about'
    get 'contact', to: 'page#contact' 
    

    resources :blogs do
     member do
         get :toggle_status
     end
    end
  
    

    resources :portfolios, except: [:show]
    get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
    get 'angular-items', to: 'portfolios#angular'
  end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  include Placeholder

  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies, reject_if: lambda { |attrs| attrs['name'].blank? }

validates_presence_of :title, :body, :main_image, :thumb_image

def self.angular
  where(subtitle: 'Angular')
end
scope :ruby_on_rails_porrfolio_items, -> { where(subtitle: 'Ruby on Rails')}

after_initialize :set_defaults


def set_defaults
  self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
  self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  def index

    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    
    if @portfolio_item.save
      redirect_to portfolios_path, notice: "Portfolio items was successfully created"
    else
      render :new
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
    3.times { @portfolio_item.technologies.build }
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])
    
    if @portfolio_item.update(portfolio_params)
      redirect_to @portfolio_item
    else
      render :edit
    end
  end

  def destroy
    @portfolio_item =Portfolio.find(params[:id])
    @portfolio_item.destroy
    redirect_to portfolios_path
  end

   private

   def portfolio_params
   params.require(:portfolio).permit(:title, 
                                    :subtitle, 
                                    :body,
                                    :image,
                                    technologies_attributes: [:name]
                                    )

    
   end
 end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<h1>New Form</h1>



<%= form_for @portfolio_item do |f| %>
 <div class="field">
   <%= f.label :title %>
   <%= f.text_field :title %>
 </div>

 <div class="field">
   <%= f.label :subtitle %>
   <%= f.text_area :subtitle %>
 </div>

 <div class="field">
   <%= f.label :body %>
   <%= f.text_area :body %>
 </div>

 <div class="field">
   <%= f.label :main_image %>
   <%= f.text_area :main_image %>
 </div>

 <div class="field">
   <%= f.label :thumb_image %>
   <%= f.text_area :thumb_image %>
 </div>

<div class="actions">
   <%= f.submit %>
 </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>

<p><%= portfolio_item.subtitle %></p>

<p><%= portfolio_item.body %></p>

<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
<%= link_to "Edit", edit_portfolio_url(portfolio_item) if logged_in?(:site_admin) %>
<%= link_to "Delete", portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create new Item", new_portfolio_path if logged_in?(:site_admin) %>

<% @angular_portfolio_items.each do |p| %>
 <p><%= link_to p.title, portfolio_show_path(p) %></p>
 <p><%= p.subtitle %></p>
 <p><%= p.body %></p>
 <p><%= image_tag p.thumb_image unless p.thumb_image.nil? %></p>

 <% link_to "Edit", edit_portfolio_path(p) if logged_in?(:site_admin) %>
 <% link_to "Delete", portfolio_path(p), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit Portfolios</h1>

<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/home.html.erb
<h1>HELLO</h1>

app/views/portfolios/index.html.erb
<h1>Portfolio Index</h1>

<%= link_to "create new", new_portfolio_path if logged_in?(:site_admin) %>

<%= render partial: 'portfolio_item', collection: @portfolio_items%>
  

app/views/portfolios/new.html.erb
<h1>New Portfolio Item</h1>


<%= render 'form', portfolio_item: @portfolio_item %>

app/views/portfolios/show.html.erb
<h1>Show Portfolio</h1>


<p><%= @portfolio_item.title %></p>
<p><%= @portfolio_item.subtitle %></p>
<p><%= @portfolio_item.body %></p>
<p><%= image_tag @portfolio_item.main_image unless @portfolio_item.thumb_image.nil? %></p>

<% @portfolio_item.technologies.each do |t| %>
  <p><%= t.name %></p>
  <%end %>