config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names:{sign_in: 'login', sign_out:'logout',sign_up: 'register' }
    



    
    root to: 'page#home'    
    
    get 'about_me', to: 'page#about'
    get 'contact', to: 'page#contact' 
    

    resources :blogs do
     member do
         get :toggle_status
     end
    end
  
    

    resources :portfolios, except: [:show]
    get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
    get 'angular-items', to: 'portfolios#angular'
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
    friendly_id :title, use: :slugged

validates_presence_of :title, :body
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end
end

app/models/guest_user.rb
class GuestUser < User
  attr_accessor :name, :first_name, :last_name, :email
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  include Placeholder

  has_many :technologies, dependent: :destroy
  accepts_nested_attributes_for :technologies, reject_if: lambda { |attrs| attrs['name'].blank? }

validates_presence_of :title, :body, :main_image, :thumb_image

def self.angular
  where(subtitle: 'Angular')
end
scope :ruby_on_rails_porrfolio_items, -> { where(subtitle: 'Ruby on Rails')}

after_initialize :set_defaults


def set_defaults
  self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
  self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
end
end

app/models/skill.rb
class Skill < ApplicationRecord
validates_presence_of :title, :percent_utilized
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title 
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
validates_presence_of :name

  def first_name
  self.name.split.first
  end

  def last_name
    self.name.split.last
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception 
  include DeviseWhitelist
  include SetSource
  include CurrentUserConcern
  include DefaultPageContent
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.page(params[:page]).per(5)
    @page_title = "My Portfolio Blog"
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end

    redirect_to blogs_path
  end
  


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/concerns/set_source.rb
module SetSource
  extend ActiveSupport::Concern

  included do 
    before_filter :set_source
  end

  def set_source
    session[:source] = params[:q] if params[:q]
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  def index

    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
    
    if @portfolio_item.save
      redirect_to portfolios_path, notice: "Portfolio items was successfully created"
    else
      render :new
    end
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])
  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
    3.times { @portfolio_item.technologies.build }
  end

  def update
    @portfolio_item = Portfolio.find(params[:id])
    
    if @portfolio_item.update(portfolio_params)
      redirect_to @portfolio_item
    else
      render :edit
    end
  end

  def destroy
    @portfolio_item =Portfolio.find(params[:id])
    @portfolio_item.destroy
    redirect_to portfolios_path
  end

   private

   def portfolio_params
   params.require(:portfolio).permit(:title, 
                                    :subtitle, 
                                    :body,
                                    :image,
                                    technologies_attributes: [:name]
                                    )

    
   end
 end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper style = ''
    if current_user.is_a?(GuestUser) 
     (link_to "Register", new_user_registration_path, class: style) +
     " ".html_safe +
     (link_to "Login", new_user_session_path, class: style) 
    else
    link_to "Logout", destroy_user_session_path, method: :delete, class: style  
     end 
  end

  def source_helper(layout_name)
   if session[:source]
    greeting ="Thanks for visting me from #{session[:source]}"
    content_tag(:p, greeting, class: "source-greeting")
    end
  end


  def copyright_generator
  TravisViewTool::Renderer.copyright 'Austyn', 'All rights resevered'
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 


    <title><%= @page_title%></title>
    <%= csrf_meta_tags %>

    <meta name="Keywords" content="<%= @seo_keywords %>" />

    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

        <%= render "shared/application_nav"%>
        

        <%= yield %>

        <%= render "shared/application_footer"%>
      

        <%= source_helper("application") %>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    
    <title><%= @page_title%></title>
    <%= csrf_meta_tags %>

    <meta name="Keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  
  <%= render 'shared/blog_nav' %>
  <%= render 'shared/blog_masthead' %>
 
  <div class="container">

    
    <div class="row">
     

        <%= yield %>

        
        <%= render 'shared/blog_sidebar' %>
      </div>

      <%= render 'shared/blog_footer' %>
          
        

      <%= source_helper("blog") %>
      
    </div>
  </body>
</html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <meta name="Keywords" content="<%= @seo_keywords %>" />

    <%= stylesheet_link_tag    'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= render "shared/nav", location: 'top' %>
    
    <%= login_helper %>

    <%= yield %>
    
    <%= source_helper("application") %>
  </body>
</html>

app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Hi, My name is Caelen Austyn Travis, I like to go by Austyn. I am 22 years old, and currently living in utah. I am a web devloper from bottega</p>

app/views/page/contact.html.erb
<h1>Would you like to work together?</h1>

<hr>

<div class="row">
  <div class="col-md-6">
  <h3>Address</h3>

  <p>4040 South 685 East, Murray Utah 84107 </p>

<p>Phone number to reach me at </p>
<p><%= number_to_phone "8013093085" %></p>

<h3>Email</h3>
<p><a href="mailto:Austyntravis9@gmail.com?subject=PortfolioContact" "email me">Email me</a></p>

<div class ="col-md-6">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3025.5649817868616!2d-111.8750186843342!3d40.68355304729187!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x87528a6c3b4deb39%3A0xa380d6d852629d09!2s4040+S+685+E%2C+Murray%2C+UT+84107!5e0!3m2!1sen!2sus!4v1485284225918" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
</div>
</div>

app/views/page/home.html.erb
<div class="inner cover">
   <h1 class="cover-heading">Welcome</h1>
   <p class="lead"> <b>to the best page on the internet</b> </p>
   <p class="lead">
     <%= link_to "About me", about_me_path, class: "btn btn-lg btn-secondary" %>
   </p>
 </div>

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Austyn Travis</h3>
    <nav class="nav nav-masthead">
      <%= link_to "Home", root_path, class: 'nav-link' %>
      <%= link_to "About", about_me_path, class: 'nav-link' %>
      <%= link_to "Contact", contact_path, class: 'nav-link' %>
      <%= link_to "Blog", blogs_path, class: 'nav-link' %>
      <%= link_to "Portfolios", portfolios_path, class: 'nav-link' %>
      <%= login_helper 'nav-link' %>

    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
    <div class="container">
      <h1 class="blog-title">My Blog</h1>
      <p class="lead blog-description">An example blog template built with Bootstrap.</p>
      <%= link_to 'Right a new blog', new_blog_path if logged_in?(:site_admin) %>
    </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= link_to "Home", root_path, class: 'nav-link' %>
      <%= link_to "About", about_me_path, class: 'nav-link' %>
      <%= link_to "Contact", contact_path, class: 'nav-link' %>
      <%= link_to "Blog", blogs_path, class: 'nav-link' %>
      <%= link_to "Portfolios", portfolios_path, class: 'nav-link' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon "github"%></a></li>
      <li><a href="#"><%= fa_icon "instagram"%></a></li>
      <li><a href="#"><%= fa_icon "facebook"%></a></li>
      <li><a href="#"><%= fa_icon "twitter"%></a></li>
      
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%=location%>">

<div>
<%= link_to "Home", root_path %>
<%= link_to "About", about_me_path %>
<%= link_to "Contact", contact_path %>
<%= link_to "Blog", blogs_path %>
<%= link_to "Portfolios", portfolios_path %>
</div>